; From that Assembly book...
		ORG		7000H
VIDEO	EQU		3C00H
START	LD		HL,VIDEO	;SOURCE
		LD		DE,VIDEO+1	;DEST. ADDRESS
		LD		BC,400H		;BYTE COUNT
		LD		(HL),0BFH	;GRAPHICS BYTE
		LDIR
;DELAY LOOP TO KEEP WHITED-OUT SCREEN ON
		LD		B,5
LP1		LD		HL,0FFFFH	;VALUE TO DECREMENT
LP2		DEC		HL
		LD		A,H
		OR		L			;HL=0?
		JP		NZ,LP2		;IF NO DEC AGAIN
		DJNZ	LP1			;DEC.B--B=0?
		CALL	$402d		;EXIT TO OS
;		JP		0H			;RETURN TO BASIC
		END		START

